### ISSUE TITLE
Docs needs better formatting and ToC

### ISSUE THREAD

**Issue by tcrowe** [botupdate/botupdate#3]
This repo would benefit from better formatting.

Markdown syntax:
https://daringfireball.net/projects/markdown/syntax

GFM - GitHub-flavored Markdown
https://github.github.com/gfm/

Table of Contents is harder but the basic idea is to create a link to a heading's anchor.

Create heading

```md
## Table of Contents

+ [Adversarial Neural Network](#adversarial-neural-network)
+ [Advanced Persistent Threat](#advanced-persistent-threat)

## Adversarial Neural Network

ANN paragraphs...

## Advanced Persistent Threat

APT paragraphs...
```

Something like that will do it. Good luck if you can try and pull it off! 👍🏻

**Comment by tcrowe** [comment]
And of course normal English syntax needs work. The paragraphs are too long.

**Comment by cynthiayoung536** [comment]
People need help with understanding why and who are hacking and destroying everything about them and getting help with processing for all involved doing it
