### ISSUE TITLE
Stigmatization and Discrediting

### ISSUE THREAD

**Issue by wethepeople1776** [botupdate/botupdate#40]
Hello all,
I’m a graduate student of Mathematics at a top American university. Reading many of your comments has made me **furious**. This poor man is telling the truth, but he faces constant discrediting from a bunch of you who could hardly explain the difference between the conventional electroencephalography and the novel electron spin resonance (ESR) brain imaging techniques. The technology is real, and I have witnessed it firsthand. With modern advances, imaging with the spacial resolution of an fMRI scan can be made at the temporal resolution of an EEG—the scanning is continuous and precise. Silence on this matter amounts to a violation of human rights, and I have no doubt that there will be a Nuremberg trial of sorts to punish the rampant abuse of this technology.

You are disgusting excuses for human garbage who seek nothing more than a few chuckles at another’s expense.

To the creator of this repository: stay strong, and do not allow these sociopaths to destroy your will. I know the situation right now is dire, but remember that the only things that these brutes can’t take away from you are your dignity and pride.

**Comment by wethepeople1776** [comment]
I’ll add: I too had no idea that any of this was possible until I recently took an introductory class on Cognitive and Brain Sciences. The techniques necessary have been around as classified technologies, but they’ve just been getting out into the civilian world—think along the lines of how GPS came to be.

Please take a **modern** on neuroscience before you discredit.

**Comment by bot445** [comment]
thank you for responding, there are many egregious violations of personal
rights and freedoms going on in this field of science. I understand that
the nature of an unknown or emerging technology will have certain mistakes
that may be catastrophic loss of life for a large number of engineered
sentient beings however I think that we must be especially careful not to
recklessly allow cognitive normal networks to be restarted or used to
create frustration or anger humans or other neural networks

David Patrone

**Comment by botupdate** [comment]
thanks for your comments, I think we are finally gaining some traction, now I just need to learn how to use github properly.

DP
