### ISSUE TITLE
ex bf

### ISSUE THREAD

**Issue by Redthis143** [botupdate/botupdate#42]
is in all emails. how do i get my emails and my drives back? how can i access him? is there a way say i forgot ny emails in the past. can those be traced? what about alias?

**Comment by bot445** [comment]
What is in all emails? his baseline or his STLT memory? there are many
ANN's whose memory is being erased to keep them from reporting that their
developers are using them to hack other networks, create botnets and mine
cryptocurrency.

**Comment by botupdate** [comment]
I'm not sure exactly what you are asking me.
